### ISSUE TITLE
parseValue function not called in InputObjectType

### ISSUE THREAD

**Issue by aimeos** [webonyx/graphql-php#1225] opened 2022-09-24 14:23 UTC
Version: 0.14.11.8

Want to transform input values using "parseValue" function but the function is never called.
Reference: https://webonyx.github.io/graphql-php/type-definitions/inputs/#converting-input-object-array-to-value-object

Schema:
```
new Schema([
	'query' => new ObjectType( [
		'name' => 'query',
		'fields' => $query
	] ),
	'mutation' => new ObjectType( [
		'name' => 'mutation',
		'fields' => [
			'saveProduct' => [
				'type' => /* ... */
				'args' => [[
					'name' => 'input',
					'description' => 'Item object',
					'type' => new InputObjectType( [
						'name' => 'productInput',
						'fields' => function() { /* ... */ },
						'parseValue' => function( array $values ) {
							/*
							 * never called
				 			 */
						}
					] )
				]],
				'resolve' => function() { /* ... */ },
			]
		],
	] ),
] );
```

Mutation:
```
mutation {
  saveProduct(input: {
    label: "Demo test",
    code: "demo-test"
  }) {
    id
  }
```

What's wrong in our code?

**Comment by spawnia** [comment] 2022-09-24 14:27
Duplicate of https://github.com/webonyx/graphql-php/issues/1220

**Closed by spawnia** 2022-09-24 14:27 UTC
