### ISSUE TITLE
Recursive types cause an infinite loop in a schema defined with type language (schema.graphql)

### ISSUE THREAD

**Issue by bryan-havenly** [webonyx/graphql-php#179] opened 2017-10-05 22:47 UTC
Example schema file:
```
interface Thing {
  id: ID!
}

type Query {
  userList: [User]
}

type User implements Thing {
  id: ID!
  self: User
}
```

Using a schema like this causes requests to fail with a 504 because the type resolution step of the schema never finishes.

I've done some digging and the request makes it through AST parsing, into a `BuildSchema::buildAST()` call, and finally fails during schema decorating whenever the fields of User are resolved (resolved by calling the `Closure` that is initially returned).

**Comment by bryan-havenly** [comment] 2017-10-05 22:58
I read through the source of `GraphQL\Utils\BuildSchema` a little looking for the issue and it seems like it might be this chain of functions:
```
makeTypeDefConfig => makeFieldDefMap => produceOutputType => produceType => 
typeDefNamed => makeSchemaDefConfig => makeTypeDefConfig => etc...
```

**Comment by vladar** [comment] 2017-10-06 03:59
So it fails not when you create a schema, but when you issue a query against it, right?

**Comment by bryan-havenly** [comment] 2017-10-06 15:26
It fails during a request, but the infinite loop happens during the `BuildSchema::buildAST` call, not during `GraphQL::executeQuery`

**Comment by vladar** [comment] 2017-10-06 18:31
I just tried, but it worked for me. Look at the test case below and help me reproduce your situation:

```php
    public function testRecursiveTypes()
    {
        $body = '
interface Thing {
  id: ID!
}

type Query {
  userList: [User]
}

type User implements Thing {
  id: ID!
  self: User
}
';
        $doc = Parser::parse($body);

        $schema = BuildSchema::buildAST($doc);
        $this->assertInstanceOf(Schema::class, $schema);
    }
```

I also tried executing a query against this schema and all worked fine. What should I add to see the bug?  

Also please make sure that it's not your `typeConfigDecorator` which causes the error (i.e. maybe it adds `fields` as array vs Closure)

**Comment by bryan-havenly** [comment] 2017-10-07 01:19
I'm actually leaving on a vacation, but I work with @jrichard0725 and we've been having the same issue, so he can provide the code to reproduce.

I think the issue actually *is* triggered by `typeConfigDecorator`, because at one point we call the `fields` Closure returned by the User type (`$typeConfig['fields']()`) in order to provide `resolve` functions for some of it's fields. It seems like whenever that Closure is called it attempts to resolve the types of the fields and recurses into oblivion.

Anyway, @jrichard0725 can get you some code to reproduce this on Monday.

**Comment by vladar** [comment] 2017-10-07 06:43
@bryan-havenly I think it's because you call `$typeConfig['fields']()` inside typeConfigDecorator itself.

Instead you should redefine $typeConfig['fields'] with your own closure and call previous one inside it. I.e.:

```php
$typeConfigDecorator = function ($typeConfig) {
    if ($typeConfig['name'] === 'MyObjType') {
        $fieldsFn = $typeConfig['fields'];
        // Note: you shouldn't call this $fieldsFn here, instead redefine 'fields' 
        // and call from there:
        $typeConfig['fields'] = function () use ($fieldsFn) {
            $fields = $fieldsFn();
            // do whatever you need with $fields here
            return $fields;
        }
    }
    return $typeConfig;
}
```

**Comment by jrichard0725** [comment] 2017-10-09 16:34
@vladar I will give that a try today and see if it resolves our issue. Thanks

**Comment by jrichard0725** [comment] 2017-10-10 05:50
@vladar this indeed solved our issue. Thanks - You can close this request.

**Closed** 2017-10-10 07:46 UTC
