### ISSUE TITLE
BC break with GraphQL\Server\ServerConfig::setValidationRules signature in 14.11.7

### ISSUE THREAD

**Issue by andrew-demb** [webonyx/graphql-php#1221] opened 2022-09-21 10:02 UTC
Signature of `GraphQL\Server\ServerConfig::setValidationRules` (https://github.com/webonyx/graphql-php/blob/688c6b7fae513c912581d3f9e141161fe5729191/src/Server/ServerConfig.php#L213) has been changed in `v14.11.7`.

Signature in `v14.11.6` - https://github.com/webonyx/graphql-php/blob/6070542725b61fc7d0654a8a9855303e5e157434/src/Server/ServerConfig.php#L168) were not declared explicit return type.

As of this method marked as `@api` there were expectations about strong BC promise.
For now this update breaks `thecodingmachine/graphqlite-bundle` https://github.com/thecodingmachine/graphqlite-bundle/blob/3ae908cc814dfa7283d869789db5852a200a46aa/Server/ServerConfig.php#L27

Proposed solution: revert changing method signature and apply this change only with next major version bump with changelog

**Comment by RikvdHeijden** [comment] 2022-09-21 10:18
This version breaks basically every class that extends from this library in some way. Notable Magento 2 that extends the types and now throws an error because the $name attributes has suddenly been typed as a string.

**Comment by mfn** [comment] 2022-09-21 10:31
I think the problem is that the release has been made from the wrong branch, from master, but should have been from the 14.x branch.

Because that type change was done later year… but we had a release in April, not containing it.

Is that possible?

**Comment by spawnia** [comment] 2022-09-21 10:40
> I think the problem is that the release has been made from the wrong branch, from master, but should have been from the 14.x branch.
> 
> Because that type change was done last year… but we had a release in April, not containing it.
> 
> Is that possible?

Yup, that is it - my bad. Will fix ASAP.

**Comment by possi** [comment] 2022-09-21 11:15
Other problems we run into:
* `Type of App\GraphQL\Type\EmailType::$description must be ?string (as in class GraphQL\Type\Definition\ScalarType)` (could be fixed in our project)
* `Access to an undefined property GraphQL\Type\Definition\Type::$name` (could be fixed in our project)
* But worst: `Overblog\DataLoader\Promise\Adapter\Webonyx\GraphQL\SyncPromiseAdapter::beforeWait(GraphQL\Executor\Promise\Promise $promise) must be compatible with GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter::beforeWait(GraphQL\Executor\Promise\Promise $promise): void` Requires Update in 3rdParty-Project: [overblog/dataloader-php](https://github.com/overblog/dataloader-php/blob/master/src/Promise/Adapter/Webonyx/GraphQL/SyncPromiseAdapter.php)

**Comment by mfn** [comment] 2022-09-21 11:29
Best field test ever 😅

Basically what everyone got was/is 15.x .

Not sure if it's meant to be, but https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md#v14xx--v15xx does not list those things; it only has 2 items.

**Comment by mfn** [comment] 2022-09-21 11:54
Possibly related: https://github.com/rebing/graphql-laravel/discussions/944

**Comment by spawnia** [comment] 2022-09-21 15:27
Sorry for the trouble everybody, I just fixed the release to point to a tag on the correct branch - see https://github.com/webonyx/graphql-php/releases/tag/v14.11.7.

**Closed by spawnia** 2022-09-21 15:27 UTC

**Comment by spawnia** [comment] 2022-09-21 15:33
> Not sure if it's meant to be, but [master/UPGRADE.md#v14xx--v15xx](https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md?rgh-link-date=2022-09-21T11%3A29%3A14Z#v14xx--v15xx) does not list those things; it only has 2 items.

The changelog should list all breaking changes, not all of them are properly documented.

**Comment by brandonkelly** [comment] 2022-09-21 17:42
Agree it would be nice if it were `14.11.7.1` or something. We’ve already released a Craft CMS release explicitly listing `14.11.7` as a conflicting package/version.
