### ISSUE TITLE
FatalError when TypeError is thrown

### ISSUE THREAD

**Issue by otzy** [webonyx/graphql-php#404] opened 2018-11-23 14:49 UTC
I get this FatalError:
`Type error: Argument 1 passed to GraphQL\Executor\ExecutionContext::addError() must be an instance of GraphQL\Error\Error, instance of TypeError given, called in /vendor/webonyx/graphql-php/src/Executor/Executor.php on line 316`

If in ExecutionContext class line 88 I change typehint to Throwable, then I get regular GrophQl response with an error description
```
public function addError(Error $error)
```

change to 
```
public function addError(\Throwable $error)
```

webonyx/graphql-php version 0.12.6

**Comment by vladar** [comment] 2018-11-27 11:03
But can you share what TypeError do you get there (message, trace)? Your fix won't work for everyone as ExecutionContext is expected to contain GraphQL Errors only.

**Comment by otzy** [comment] 2018-11-28 22:48
there was a bunch of closures in the trace, I'll try to reproduce

**Comment by otzy** [comment] 2018-11-29 13:19
This is the top of trace.
To reproduce I defined type as something other than GraphQL\Type\Definition\Type
It can be stdClass or even scalar, does not matter 

```
(1/1) FatalThrowableErrorType error: Argument 1 passed to GraphQL\Executor\ExecutionContext::addError() must be an instance of GraphQL\Error\Error, instance of TypeError given, called in vendor/webonyx/graphql-php/src/Executor/Executor.php on line 316
--
in ExecutionContext.php line 88
at ExecutionContext->addError(object(TypeError))in Executor.php line 316
at Executor->GraphQL\Executor\{closure}(object(TypeError))in SyncPromise.php line 144
at SyncPromise->GraphQL\Executor\Promise\Adapter\{closure}()in SyncPromise.php line 35
at SyncPromise::runQueue()in SyncPromiseAdapter.php line 140
at SyncPromiseAdapter->wait(object(Promise))in GraphQL.php line 88
at GraphQL::executeQuery(object(Schema), '{ getUser(db_id: 123){ name } profiler{ log }}', array(), object(PlayWithRelayController), null)in PlayWithRelayController.php line 83

```

**Comment by vladar** [comment] 2018-12-01 15:48
The idea is that you don't run queries against an invalid schema. We don't have runtime validation of the schema because of performance. But you should do it separately via `$schema->assertValid();` during development.

Please try it and let me know if it reports an appropriate error. If so then this is not a bug.

**Comment by otzy** [comment] 2018-12-03 13:55
`$schema->assertValid();` throws an exception with a suggestion to run assertValid():
`One of the schema types is not a valid type definition instance. Try running $schema->assertValid() to find out the cause of this warning.`
In the trace it's possible to find what was the invalid type, but it's not clear where it comes from. It would be nice to see a path to error node in a future release.

Regarding the type hint in the addError() function - now it works in a way that we don't expect from exceptions. It replaces the real exception with unrelated one.
And general thought -  if a function called with an argument of wrong type it's a programmatic error. In this case addError() is called by another function of the same package, not from outside, so this looks like a bug.

**Comment by vladar** [comment] 2019-06-19 12:02
Should be fixed in master, please check when you have a chance (both $schema->assertValid() and direct execution without schema validation).

**Closed by vladar** 2019-06-19 12:02 UTC
Labels: bug
