### ISSUE TITLE
Parse error with empty directive

### ISSUE THREAD

**Issue by brunobg** [webonyx/graphql-php#719] opened 2020-08-24 14:16 UTC
I'm getting this error:

```
   GraphQL\Error\SyntaxError 

  Syntax Error: Expected "on", found BlockString "Register a type for Relay's global object identification.
When used without any arguments, Lighthouse will attempt
to resolve the type through a model with the same name."

  at vendor/webonyx/graphql-php/src/Language/Parser.php:282
    278|             $this->lexer->advance();
```

It happens when parsing the `schema-directives.graphql` file from https://github.com/nuwave/lighthouse, more specifically here:

```graphql
# Directive class: Nuwave\Lighthouse\Schema\Directives\NestDirective
# Add a proper definition by implementing Nuwave\Lighthouse\Support\Contracts\DefinedDirective
directive @nest

# Directive class: Nuwave\Lighthouse\Schema\Directives\NodeDirective
"""
Register a type for Relay's global object identification.
When used without any arguments, Lighthouse will attempt
to resolve the type through a model with the same name.
"""
```

Apparently an empty directive does not parse properly, but it seems to be valid https://spec.graphql.org/June2018/#sec-Language.Directives.

I'm running graphql-php 0.13.9 and lighthouse 4.16.1. Version 14 is not compatible with the latest release of lighthouse, so I couldn't test with it.

**Comment by spawnia** [comment] 2020-08-24 19:39
> Apparently an empty directive does not parse properly, but it seems to be valid spec.graphql.org/June2018/#sec-Language.Directives.

It is not valid. What you are linking to is directive usage. Directive definition requires the locations: https://spec.graphql.org/June2018/#sec-Type-System.Directives

This library is correct, the issue is with Lighthouse. Fixed in https://github.com/nuwave/lighthouse/commit/6009ed20ea87a523a29dcd4f79c1b8ec5a116356 and released in https://github.com/nuwave/lighthouse/releases/tag/v4.16.2

**Closed by spawnia** 2020-08-24 19:39 UTC
