### ISSUE TITLE
Allow deprecating arguments

### ISSUE THREAD

**Issue by ruudk** [webonyx/graphql-php#1312] opened 2023-02-14 13:46 UTC
It seems that this is not supported by graphql-php but is allowed in the spec: https://github.com/graphql/graphql-spec/pull/525

**Comment by spawnia** [comment] 2023-02-14 14:16
Duplicate of https://github.com/webonyx/graphql-php/issues/110

**Closed by spawnia** 2023-02-14 14:16 UTC

**Comment by ruudk** [comment] 2023-02-14 14:24
Can you update that issue to also explain it's related to arguments?
