### ISSUE TITLE
Allow deprecation of input fields

### ISSUE THREAD

**Issue by jasonbahl** [webonyx/graphql-php#155] opened 2017-08-24 18:48 UTC
Is it possible to Deprecate input fields? 

In playing around a bit, it doesn't seem like an option right now, but wanted to confirm before diving too deep.

**Comment by vladar** [comment] 2017-08-24 18:56
This is not specified yet. 

See https://github.com/facebook/graphql/issues/197 for details. I'll close this issue for now, but will get back to it as soon as this feature gets reflected in the specification.

**Comment by grzegorzstachniukalm** [comment] 2020-12-04 13:01
https://github.com/graphql/graphql-spec/pull/525 it's merged

**Comment by spawnia** [comment] 2021-07-29 15:38
Duplicate of https://github.com/webonyx/graphql-php/issues/155

**Closed by spawnia** 2021-07-29 15:38 UTC
Labels: enhancement

**Comment by jasonbahl** [comment] 2021-07-29 18:56
> Duplicate of #155

I believe you meant: Duplicate of #110 😄
