### ISSUE TITLE
Having fields of interface type

### ISSUE THREAD

**Issue by mikelikenike** [webonyx/graphql-php#378] opened 2018-10-24 23:05 UTC
Hi, am I not allowed to have fields with a type of a class extended from GraphQL\Type\Definition\InterfaceType? I tried that and ended with this error: "Schema must contain unique named types but contains multiple types named MyType" even though I checked my code and the only place where I create a new MyType is statically in my Types class.

Would the right approach be creating a class extending GraphQL\Type\Definition\UnionType and list the types(which implement my interface type) there?

Thanks

**Comment by vladar** [comment] 2018-10-25 10:59
This error means that you unintentionally create multiple instances of the same type (either somewhere in your type definitions or in your `resolveType` method). Instead of creating new type instance you must always re-use the same instance of a type (within one schema).

So double check where your types are being created (with the `new` keyword). My first guess is that you do it somewhere in the `resolveType` method of your interface type.

**Comment by mikelikenike** [comment] 2018-10-27 00:06
The only place I create a new type is in my Types class

`
public class Types {
public static function typeA(): TypeA
    {
        return self::$typea?: (self::$typea = new TypeA());
    }
public static function typeB(): TypeB
    {
        return self::$typeb?: (self::$typeb = new TypeB());
    }
public static function node(): NodeInterface
    {
        return self::$node ?: (self::$node = new NodeInterface());
    }
}
`
Both my types implement the NodeInterface.
`
class NodeInterface extends InterfaceType
{
    public function __construct()
    {
        $config = [
            'name' => 'Node',
            'fields' => [
                'title' => Type::string(),
            ],
            'resolveType' => function ($value, $context, ResolveInfo $info) {
                switch ($value->getType()) {
                    case 'typea':
                        return TypeRegistry::TypeA();
                    case 'typeb':
                        return TypeRegistry::TypeB();
                }
            },
        ];
        parent::__construct($config);
    }
}

public TypeA extends ObjectType
{
public function __construct()
  $config = [
            'name' => 'Type A',
            'interfaces' => [
                TypeRegistry::node(),
            ],
        ];
        parent::__construct($config);
}
}

public TypeB extends ObjectType
{
public function __construct()
  $config = [
            'name' => 'Type B',
            'interfaces' => [
                TypeRegistry::node(),
            ],
        ];
        parent::__construct($config);
}
}
`

In my query class, I want to do something like this:

`
$config = [
            'name' => 'Query',
                'providers' => [
                    'type' => Type::listOf(TypeRegistry::node()),
                ],
            ],
        ];
`

but it only seems to work if my result set is of the same type(either TypeA or TypeB). If I have a result set that contains objects of both types, that is when I get the error. So what I want to know is if this is feasible with both my types?

**Comment by vladar** [comment] 2018-11-21 10:37
This should definitely work with mixed types. Can you create a reproducible test case for it (either in a separate github project or ideally as a phpunit test case)?

**Comment by vladar** [comment] 2019-04-21 09:35
Closing due to lack of information. Feel free to re-open with a reproducible test case.

**Closed by vladar** 2019-04-21 09:35 UTC

**Comment by quadrifolia** [comment] 2019-06-07 20:23
Just run into the same "problem". It happens because TypeA and TypeB are not explicitly used in any query. They are only used in the resolveType function of the interface. So `GraphQL\Utils\TypeInfo::resolveInfo()` will not find these types.

I used the[ types option](https://webonyx.github.io/graphql-php/type-system/schema/#configuration-options) on the schema to register these "lost" types.
