### ISSUE TITLE
Add `extensions` property to all types and fields configs

### ISSUE THREAD

**Issue by SevInf** [webonyx/graphql-php#623] opened 2020-02-25 13:48 UTC
For example:

```php
<?php
return new ObjectType([
    'name' => 'MyType',
    'extensions' => [
        'someTypeProperty' => 'value'
    ],
    'fields' => [
        [
            'name' => 'myField',
            ...
            'extensions' => [
                'someFieldProperty' => 'value'
            ]
        ]
    ]
])

```

`graphql-js` did it in graphql/graphql-js#2097.

This is a convenient way to add additional metadata for fields and types and access this data in the resolver. To the extent, it will work right now because 'graphql-php' allows to add custom properties, but in won't work in 100% cases. For example, `SchemaExtender` class will erase all non-standard properties on the config.

**Comment by vladar** [comment] 2020-02-26 09:29
It sounds like a duplicate of #588. Closing this to keep all context in a single issue.

**Closed by vladar** 2020-02-26 09:29 UTC
