### ISSUE TITLE
Enum returns incorrect case

### ISSUE THREAD

**Issue by martio** [webonyx/graphql-php#1626] opened 2024-11-06 10:54 UTC
**Description:** When querying an enum in the Lighthouse GraphQL API, the enum values are returned with only the first letter capitalized, which does not align with the expected uppercase format. For instance, when querying the UserStatus enum, values are returned as "Active", "Inactive", etc., instead of "ACTIVE", "INACTIVE", etc.

**Expected Behavior:** The enum values should be returned in uppercase, matching the convention in GraphQL specifications and our application requirements.

**Steps to Reproduce:**

Define a native PHP enum with lowercase values, as follows:

```php
enum StatusEnum: string {
    case INACTIVE = 'inactive';
    case ACTIVE = 'active';
    case BANNED = 'banned';
}
```

Configure the enum in Lighthouse:

```graphql
enum UserStatus {
    INACTIVE @enum(value: "inactive")
    ACTIVE @enum(value: "active")
    BANNED @enum(value: "banned")
}
```

Execute a GraphQL query that retrieves this enum:

```graphql
query {
  user(id: 1) {
    id
    status
  }
}
```

Observe the format of the returned enum value.

Current Response:

```json
{
  "data": {
    "user": {
      "id": 1,
      "status": "Active"
    }
  }
}
```

Expected Response:

```json
{
  "data": {
    "user": {
      "id": 1,
      "status": "ACTIVE"
    }
  }
}
```

**Comment by spawnia** [comment] 2024-11-07 14:55
Duplicate of https://github.com/webonyx/graphql-php/issues/1626, it is more appropriate there.

**Closed by spawnia** 2024-11-07 14:55 UTC

**Comment by martio** [comment] 2024-11-07 15:21
@spawnia I think you provided the wrong link to the duplicate... 😉

**Comment by martio** [comment] 2024-11-07 19:55
@spawnia I have posted a solution in this issue: https://github.com/nuwave/lighthouse/issues/2629
