### ISSUE TITLE
Modifying context inside a resolver does not propagate to child resolvers

### ISSUE THREAD

**Issue by JohnyDays** [webonyx/graphql-php#54] opened 2016-10-06 13:17 UTC
Context is supposed to be something you can pass down to any resolver, and modify from any point, but I wasn't able to make this work without changing the line in https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L460 to
```php
return $resolveFn($source, $args, $context, $info);
```

Without this change, defining the resolve function as `function ($parent, $args, &$context, $ast) {}` is an error because of some bug/weird behaviour with call_user_func

EDIT: I've made the change in my fork over at https://github.com/JohnyDays/graphql-php/tree/directlyCallResolver, should I open a pull request, or am I missing something? Cheers!

EDIT2: I actually had to change a few more lines in the end to make it work, assigning context by reference.

**Comment by vladar** [comment] 2016-10-06 16:42
What do you use as context? Is it array or object?

**Comment by JohnyDays** [comment] 2016-10-06 17:05
An array, I don't usually use objects in my php code.

**Comment by vladar** [comment] 2016-10-06 17:45
Arrays are value objects in PHP. If you pass an object as context it will be passed by reference copy. So the quick solution would be to replace array with `new ArrayObject()` and then pass it as `$context` instead (or create an object wrapper for your context array).

I do not want to pass $context by reference because it has it's own disadvantages, including accidental null'ing and [possible performance overhead for read-only access](http://stackoverflow.com/questions/178328/in-php-5-0-is-passing-by-reference-faster/3845530#3845530).

**Comment by JohnyDays** [comment] 2016-10-06 18:17
Alright, that sounds good. I'll probably end up doing that, although I will probably keep this solution for the time being.
I find objects particularly cumbersome in PHP given that most utilities work with either objects or arrays, and only one of them (arrays) can play the part of both, but an exception for this specific case doesn't sound too bad.
Should probably close this as expected behaviour right?

**Comment by vladar** [comment] 2016-10-06 18:23
Yes, this is quite expected behavior. 

Also I am curious why do you need to modify context in resolvers? While this operation is valid but I never really needed to do this (returning custom values was usually enough). 

Just want to better understand use-cases for future lib maintenance.

**Comment by JohnyDays** [comment] 2016-10-06 19:10
The way I'm using it that I have singularly defined types somewhere, but their behaviour depends on who their parent resolvers are. E.g while the "Menu" type is unfiltered if you are logging in through the admin entry, it will be filtered if the parent route is the regular entry.

I could just pass the user through the context, or pass it down through all the resolvers, but one isn't generic and the other one sounds cumbersome. Plus I always prefer being explicit.

What I'm doing is adding to context something like 
```php
$context["rules"] = ["menu" => ["filter" => ["type"=> "userAuthentication"]];
```
On the parent resolver, and then the child resolver checks for any rules it received and acts accordingly.

Could I do this by passing it down through every resolver? Yes, but in other situations context is very necessary, such as when coordinating large transactions in a multi-threaded/event-loop scenario, which isn't the case in php, but I'm sure I could find some other problems solved by it given the time.

Also this means I can't accidentally expose the data by having a naming collision in the return type/passed down data.

Cheers 🍰  Thanks for the library, it's been insanely helpful.

**Comment by vladar** [comment] 2016-10-06 19:37
Thanks. This seems reasonable. Current user or rules depending on current user is a primary use case for context, it's just that usually it is defined on the top-level (vs in resolvers), but I guess cases like yours also make sense.

I'll close this issue, but feel free to reopen or fill another one if needed.

**Closed by vladar** 2016-10-06 19:37 UTC
